spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start-and-stop

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    # driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_ID}
            client-secret: ${GOOGLE_OAUTH_SECRET}
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/drive.file
        provider:
          google:
            # google 인증 시, refresh 토큰도 발급하도록 access_type=offline 설정
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  capsule-domain: ${CORS_CAPSULE_DOMAIN:http://localhost:3000/capsules} # 프론트의 라우팅 방식, 도메인 생성 시 바뀔 부분

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.example.demo: DEBUG

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  from-number: ${COOLSMS_FROM_NUMBER}

openai:
  api:
    key: ${OPENAI_API_KEY:}

  moderation:
    model: omni-moderation-2024-09-26
    block-on-flagged: true   # true면 flagged 시 저장 막음
    fail-closed: false        # true면 OpenAI 장애 시 저장 막음

app:
  s3:
    bucket: ${S3_BUCKET_NAME}
    prefix: capsules
    region: ${S3_REGION}

google:
  drive:
    client-id: ${GOOGLE_OAUTH_ID}
    client-secret: ${GOOGLE_OAUTH_SECRET}
    redirect-uri: ${GOOGLE_DRIVE_LOCAL_REDIRECT}

# 삭제 테스트 하고 싶으면 아래 주석 해제하세요
# 매 10초마다 하드 삭제 크론 실행입니다
#capsule:
#  hard-delete:
#    cron: "*/10 * * * * *"
