name: deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "build.gradle*"
      - "settings.gradle*"
      - "gradle/**"
      - "Dockerfile"
      - ".github/workflows/**"

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: dear-api

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      owner_lc: ${{ steps.owner.outputs.owner_lc }}
    steps:
      - uses: actions/checkout@v4

      - id: owner
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "owner_lc=$OWNER_LC" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.owner.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ build_and_push ]
    steps:
      - name: Deploy by SSM
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}
          working-directory: /
          comment: Deploy
          command: |
            cd /opt/deploy && \
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PERSONAL_ACCESS_TOKEN }} && \
            docker pull ghcr.io/${{ needs.build_and_push.outputs.owner_lc }}/${{ env.IMAGE_NAME }}:latest && \
            docker compose up -d && \
            docker image prune -f
